version: '3.8'

services:
  app:
    image: ghcr.io/erlangh/smartolt-app:latest
    container_name: smartolt-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      PORT: "3000"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "change-me-in-production-min-32-chars"
      # Gunakan SQLite sebagai default (sesuai schema.prisma provider=sqlite)
      DATABASE_URL: "file:/app/prisma/dev.db"
    volumes:
      - ./data/dev.db:/app/prisma/dev.db
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)}).on('error',()=>process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s